version: '3.8'
services:
  api:
    build: .
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
  redis:
    image: redis:7
  app-postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: mediahub
      POSTGRES_USER: mediahub
      POSTGRES_PASSWORD: example
    volumes:
      - app-postgres-data:/var/lib/postgresql/data
  minio:
    image: minio/minio
    command: server /data
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    volumes:
      - minio-data:/data
    ports:
      - "9000:9000"
volumes:
  app-postgres-data:
  minio-data:
