services:
  api:
    build: .
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
  gateway:
    image: nginx:1.25-alpine
    depends_on:
      - api
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8080:80"
  redis:
    image: redis:7
    volumes:
      - ${DATA_DIR}/redis:/data
  app-postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: mediahub
      POSTGRES_USER: mediahub
      POSTGRES_PASSWORD: example
    volumes:
      - ${DATA_DIR}/app-postgres:/var/lib/postgresql/data
  minio:
    image: minio/minio
    command: server /data
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    volumes:
      - ${DATA_DIR}/minio:/data
    ports:
      - "9000:9000"
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      - WEBUI_PORT=8080
    volumes:
      - ${DATA_DIR}/qbittorrent/config:/config
      - ${DATA_DIR}/qbittorrent/downloads:/downloads
      - ./scripts:/scripts:ro
    ports:
      - "8081:8080"
    restart: unless-stopped
