services:
  api:
    build: .
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./:/app
    environment:
      - PYTHONPATH=/app
      - BITMAGNET_RO_DSN=${BITMAGNET_RO_DSN}
    ports:
      - "8000:8000"

  web:
    image: node:20
    working_dir: /app
    volumes:
      - ./web:/app
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:8000
    command: sh -c "npm install && npm run dev"
    ports:
      - "3001:3000"
  app-postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: mediahub
      POSTGRES_USER: mediahub
      POSTGRES_PASSWORD: example
    volumes:
      - ${DATA_DIR:-/opt/seedbox}/app-postgres:/var/lib/postgresql/data
  minio:
    image: minio/minio
    command: server /data --console-address ":9090"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    volumes:
      - ${DATA_DIR:-/opt/seedbox}/minio:/data
    ports:
      - "9000:9000"
      - "9090:9090"
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      - WEBUI_PORT=8080
    volumes:
      - ${DATA_DIR:-/opt/seedbox}/qbittorrent/config:/config
      - ${DATA_DIR:-/opt/seedbox}/qbittorrent/downloads:/downloads
      - ./scripts:/scripts:ro
    ports:
      - "8081:8080"
    restart: unless-stopped
