services:
  api:
    image: golang:1.21-alpine
    working_dir: /app
    volumes:
      - ./:/app
    command: go run main.go
    ports:
      - "28000:28000"
    environment:
      - BITMAGNET_DB_HOST=${BITMAGNET_DB_HOST}
      - BITMAGNET_DB_PORT=${BITMAGNET_DB_PORT}
      - BITMAGNET_DB_USER=${BITMAGNET_DB_USER}
      - BITMAGNET_DB_PASS=${BITMAGNET_DB_PASS}
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./downloads:/downloads
      - ./watch:/watch
    ports:
      - "9091:9091"
      - "51413:51413"
      - "51413:51413/udp"
